spring.application.name=TurnoYa

spring.datasource.url=jdbc:postgresql://localhost:5432/turnoya
spring.datasource.username=postgres
spring.datasource.password=solofutbol7002

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
